version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_idrd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba_tecnica_idrd
      MYSQL_PASSWORD: idrd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend/backend_prueba_tecnica
    container_name: backend_container_idrd
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: idrd
      DB_NAME: prueba_tecnica_idrd
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm run start:dev

  frontend:
    build: ./frontend/frontend_prueba_tecnica
    container_name: frontend_container_idrd
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    command: npm start

volumes:
  mysql_data: